{"level":"ERROR","location":"[on_open:1519] data_ws","message":"name 'fyers' is not defined","timestamp":"2025-05-29 13:22:55,431+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 542, in onopen\n    fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^\nNameError: name 'fyers' is not defined. Did you mean: 'self.fyers'?","exception_name":"NameError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"name 'fyers' is not defined","timestamp":"2025-05-29 13:22:55,432+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"WebSocketConnect.onopen() missing 1 required positional argument: 'ws'","timestamp":"2025-05-29 13:24:29,869+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: WebSocketConnect.onopen() missing 1 required positional argument: 'ws'","exception_name":"TypeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"WebSocketConnect.onopen() missing 1 required positional argument: 'ws'","timestamp":"2025-05-29 13:24:29,870+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"WebSocketConnect.onopen() missing 1 required positional argument: 'ws'","timestamp":"2025-05-29 13:26:34,625+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\nTypeError: WebSocketConnect.onopen() missing 1 required positional argument: 'ws'","exception_name":"TypeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"WebSocketConnect.onopen() missing 1 required positional argument: 'ws'","timestamp":"2025-05-29 13:26:34,626+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'bool' object has no attribute 'subscribe'","timestamp":"2025-05-29 13:27:46,870+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 542, in onopen\n    self.fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'bool' object has no attribute 'subscribe'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'bool' object has no attribute 'subscribe'","timestamp":"2025-05-29 13:27:46,873+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2025-05-29 13:29:41,265+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 545, in onopen\n    self.fyers.subscribe(symbols=symbols, data_type=data_type)\n    ^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'FyersModel' object has no attribute 'subscribe'","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'FyersModel' object has no attribute 'subscribe'","timestamp":"2025-05-29 13:29:41,268+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"object of type 'NoneType' has no len()","timestamp":"2025-05-29 13:32:20,998+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1312, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'NoneType' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"object of type 'NoneType' has no len()","timestamp":"2025-05-29 13:32:20,999+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1312, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'NoneType' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'WebSocketConnect' object has no attribute 'newtoken'","timestamp":"2025-05-29 13:43:45,502+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 544, in onopen\n    symbols = asyncio.run(self.newtoken())\n                          ^^^^^^^^^^^^^\nAttributeError: 'WebSocketConnect' object has no attribute 'newtoken'. Did you mean: 'gettoken'?","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'WebSocketConnect' object has no attribute 'newtoken'","timestamp":"2025-05-29 13:43:45,504+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'WebSocketConnect' object has no attribute 'newtoken'","timestamp":"2025-05-29 13:44:18,039+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 544, in onopen\n    symbols = asyncio.run(self.newtoken())\n                          ^^^^^^^^^^^^^\nAttributeError: 'WebSocketConnect' object has no attribute 'newtoken'. Did you mean: 'gettoken'?","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'WebSocketConnect' object has no attribute 'newtoken'","timestamp":"2025-05-29 13:44:18,041+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"'WebSocketConnect' object has no attribute 'newtoken'","timestamp":"2025-05-29 13:44:49,921+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 544, in onopen\n    symbols = asyncio.run(self.newtoken())\n                          ^^^^^^^^^^^^^\nAttributeError: 'WebSocketConnect' object has no attribute 'newtoken'. Did you mean: 'gettoken'?","exception_name":"AttributeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"'WebSocketConnect' object has no attribute 'newtoken'","timestamp":"2025-05-29 13:44:49,923+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"asyncio.run() cannot be called from a running event loop","timestamp":"2025-05-29 13:45:35,999+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 544, in onopen\n    symbols = asyncio.run(self.subscribetoken())\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/asyncio/runners.py\", line 190, in run\n    raise RuntimeError(\nRuntimeError: asyncio.run() cannot be called from a running event loop","exception_name":"RuntimeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"asyncio.run() cannot be called from a running event loop","timestamp":"2025-05-29 13:45:36,000+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"asyncio.run() cannot be called from a running event loop","timestamp":"2025-05-29 13:49:09,368+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 544, in onopen\n    symbols = asyncio.run(self.subscribetoken())\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/asyncio/runners.py\", line 190, in run\n    raise RuntimeError(\nRuntimeError: asyncio.run() cannot be called from a running event loop","exception_name":"RuntimeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"asyncio.run() cannot be called from a running event loop","timestamp":"2025-05-29 13:49:09,369+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"asyncio.run() cannot be called from a running event loop","timestamp":"2025-05-29 13:50:54,522+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 544, in onopen\n    symbols = asyncio.run(self.subscribetoken())\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/asyncio/runners.py\", line 190, in run\n    raise RuntimeError(\nRuntimeError: asyncio.run() cannot be called from a running event loop","exception_name":"RuntimeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"asyncio.run() cannot be called from a running event loop","timestamp":"2025-05-29 13:50:54,523+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"Cannot run the event loop while another loop is running","timestamp":"2025-05-29 13:55:25,502+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 547, in onopen\n    symbols = loop.run_until_complete(self.subscribetoken())\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 663, in run_until_complete\n    self._check_running()\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 624, in _check_running\n    raise RuntimeError(\nRuntimeError: Cannot run the event loop while another loop is running","exception_name":"RuntimeError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"Cannot run the event loop while another loop is running","timestamp":"2025-05-29 13:55:25,504+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:00:23,386+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 553, in onopen\n    self.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n                                       ^^^^^^^\nNameError: name 'symbols' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:00:23,389+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[on_open:1519] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:00:44,013+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1517, in on_open\n    self.OnOpen()\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 553, in onopen\n    self.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n                                       ^^^^^^^\nNameError: name 'symbols' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[on_open:1520] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:00:44,016+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[__symbol_conversion:1334] data_ws","message":{"code":-300,"message":"Please provide valid inputs","s":"error","type":"sub"},"timestamp":"2025-05-29 14:01:24,081+0530","service":"FyersDataSocket","taskName":"Task-3"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"object of type 'NoneType' has no len()","timestamp":"2025-05-29 14:23:45,363+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1312, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'NoneType' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"object of type 'NoneType' has no len()","timestamp":"2025-05-29 14:23:45,364+0530","service":"FyersDataSocket","taskName":"Task-3","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1312, in __symbol_conversion\n    total_symbols = len(symbolslst)\n                    ^^^^^^^^^^^^^^^\nTypeError: object of type 'NoneType' has no len()","exception_name":"TypeError"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'token'","timestamp":"2025-05-29 14:29:50,810+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='ANGEL',symboltoken=data['token']).last()\n                                                                 ~~~~^^^^^^^^^\nKeyError: 'token'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'token' is missing in the response.","timestamp":"2025-05-29 14:29:50,812+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'token'","timestamp":"2025-05-29 14:29:50,832+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='ANGEL',symboltoken=data['token']).last()\n                                                                 ~~~~^^^^^^^^^\nKeyError: 'token'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'token' is missing in the response.","timestamp":"2025-05-29 14:29:50,833+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'token'","timestamp":"2025-05-29 14:29:53,312+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='ANGEL',symboltoken=data['token']).last()\n                                                                 ~~~~^^^^^^^^^\nKeyError: 'token'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'token' is missing in the response.","timestamp":"2025-05-29 14:29:53,313+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'token'","timestamp":"2025-05-29 14:29:53,398+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='ANGEL',symboltoken=data['token']).last()\n                                                                 ~~~~^^^^^^^^^\nKeyError: 'token'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'token' is missing in the response.","timestamp":"2025-05-29 14:29:53,400+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'token'","timestamp":"2025-05-29 14:29:53,804+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='ANGEL',symboltoken=data['token']).last()\n                                                                 ~~~~^^^^^^^^^\nKeyError: 'token'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'token' is missing in the response.","timestamp":"2025-05-29 14:29:53,804+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'symbol'","timestamp":"2025-05-29 14:31:03,743+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='FYERS',tradingsymbol=data['symbol']).last()\n                                                                   ~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'symbol' is missing in the response.","timestamp":"2025-05-29 14:31:03,744+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'symbol'","timestamp":"2025-05-29 14:31:03,761+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='FYERS',tradingsymbol=data['symbol']).last()\n                                                                   ~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'symbol' is missing in the response.","timestamp":"2025-05-29 14:31:03,761+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1442] data_ws","message":"'symbol'","timestamp":"2025-05-29 14:31:06,243+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 520, in onmessage\n    obj = md.watchlist.objects.filter(broker='FYERS',tradingsymbol=data['symbol']).last()\n                                                                   ~~~~^^^^^^^^^^\nKeyError: 'symbol'","exception_name":"KeyError"}
{"level":"ERROR","location":"[On_message:1443] data_ws","message":"KeyError: The key 'symbol' is missing in the response.","timestamp":"2025-05-29 14:31:06,249+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:36:42,815+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    elf.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n    ^^^\nNameError: name 'elf' is not defined. Did you mean: 'self'?","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:36:42,817+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:36:42,842+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    elf.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n    ^^^\nNameError: name 'elf' is not defined. Did you mean: 'self'?","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:36:42,843+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:37:33,130+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    elf.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n    ^^^\nNameError: name 'elf' is not defined. Did you mean: 'self'?","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:37:33,132+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:37:33,164+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    elf.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n    ^^^\nNameError: name 'elf' is not defined. Did you mean: 'self'?","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'elf' is not defined","timestamp":"2025-05-29 14:37:33,166+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:56,522+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    self.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n                                       ^^^^^^^\nNameError: name 'symbols' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:56,525+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:56,543+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    self.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n                                       ^^^^^^^\nNameError: name 'symbols' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:56,545+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[unsubscribe:1757] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error"},"timestamp":"2025-05-29 14:37:59,039+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:59,057+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    self.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n                                       ^^^^^^^\nNameError: name 'symbols' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:59,061+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[On_message:1446] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:59,106+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/ubuntu/Orderpunch/lib/python3.12/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1433, in On_message\n    self.OnMessage(message)\n  File \"/home/ubuntu/Orderpunch/orderpunch/Tradingbot/Brokers/fyerssdk.py\", line 536, in onmessage\n    self.websocketfy.subscribe(symbols=symbols, data_type=\"SymbolUpdate\")\n                                       ^^^^^^^\nNameError: name 'symbols' is not defined","exception_name":"NameError"}
{"level":"ERROR","location":"[On_message:1447] data_ws","message":"name 'symbols' is not defined","timestamp":"2025-05-29 14:37:59,113+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[unsubscribe:1757] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error"},"timestamp":"2025-05-29 14:38:37,934+0530","service":"FyersDataSocket"}
